# **Unsupervised Learning Methods**
## **Clustering Patient Data: A Comparative Analysis**

**Authors:** Carla Bellido García, Cindy Chen, Celica Krigul, Keith Megara Osores Vicuña, Ema Stangova
  
**Master:** Health Data Science

**Subject:** Machine Learning

**Course:** 2025-2026

---

## **Table of Contents**

**1. [Overview](#section1)**   

**2. [Dataset](#section2)**  
&emsp; **2.1 [Heart Disease UCI Dataset](#section21)**     
&emsp; **2.1 [Features](#section22)**     
  
**3. [Assignment Tasks](#section3)**  
&emsp; **3.1 [Task 1 - Data Loading & Exploration](#section31)**   
&emsp; **3.2 [Task 2 - Preprocessing & Feature Engineering](#section32)**
&emsp; **3.3 [Task 3 - Clustering: K-Means](#section33)**  
&emsp; **3.3 [Task 4 - Clustering: Gaussian Mixture Models](#section34)**  
&emsp; **3.3 [Task 5 - Clustering: Hierarchical Clustering](#section35)**  
&emsp; **3.3 [Task 6 - Clustering: Evaluation Against Ground Truth](#section36)**

---
<a id='section1'></a>
## **Overview**

In this assignment, you will apply and compare three unsupervised learning methods - **K-Means Clustering, Gaussian Mixture Models (GMM), and Hierarchical Clustering** - to a real-world medical dataset. Your goal is to discover meaningful patient subgroups *without* using the diagnostic label, then evaluate how well your clusters align with the ground truth once it is revealed.

This mirrors a real challenge in health data science: identifying patient profiles from clinical measurements alone, before a diagnosis is available. The skills you practice here - preprocessing, dimensionality reduction,  clustering, and evaluation - form the backbone of many unsupervised pipelines in healthcare.

---
<a id='section2'></a>
## **Dataset**

<a id='section21'></a>
### **Heart Disease UCI Dataset**

You will work with the Heart Disease dataset from the UCI Machine Learning Repository, publicly available at: https://archive.ics.uci.edu/dataset/45/heart+disease 

The dataset (use only processed.cleveland.data) contains 303 patient records with 13 clinical features and one target variable. You must treat the target variable as hidden during clustering, and only use it for evaluation afterwards.

<a id='section22'></a>
### **Features**

|**Feature** |**Name**                |**Description**                                             |
|------------|------------------------|------------------------------------------------------------|
|``age``     |Age                     |Age in years                                                |
|``sex``     |Sex                     |1 = male, 0 = female                                        |
|``cp``      |Chest pain type         |4 types (0-3)                                               |
|``trestbps``|Resting blood pressure  |mm Hg on admission                                          |
|``chol``    |Serum cholesterol|mg/dl |mg/dl                                                       |
|``fbs``     |Fasting blood sugar     | >120mg/dl: 1 = true, 0 = false                             |
|``restecg`` |Resting ECG results     |Values 0, 1, 2                                              |
|``thalach`` |Max heart rate achieved |Numeric                                                     |
|``exang``   |Exercise-induced angina |1 = yes, 0 = no                                             |
|``oldpeak`` |ST depression           |Induced by exercise vs. rest                                |
|``slope``   |Slope of peak ST segment|Values 0, 1, 2                                              |
|``ca``      |Major vessels (0-3)     |Coloured by fluoroscopy                                     |
|``thal``    |Thal                    |3 = normal, 6 = fixed defect, 7 = reversible defect         |
|``target``  |**Diagnosis (HIDDEN)**  |*0 = no disease, 1-4 = disease present. Binarise as 0 vs 1+*|

---
<a id='section3'></a>
## **Assignment Tasks**

The assignment follows a single end-to-end pipeline. All team members should understand every stage, even if responsibilities are divided.

<a id='section31'></a>
### **Task 1 - Data Loading & Exploration**

In [1]:
# Libraries used
import pandas as pd

- Load the dataset and display its shape, data types, and summary statistics.

In [ ]:
# Criteria: Data loaded correctly; shape, dtypes, and nulls reported.

# Load dataset
df = pd.read_csv("data/processed.cleveland.data", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [ ]:
# Add column names
cols = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target",
]

df.columns = cols
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

- Identify and handle missing values. Document your strategy and justify it.

- Plot distributions of all features (histograms, box plots).

In [ ]:
# Criteria: Histograms/box plots for all features. Observations discussed in markdown.

- Plot a correlation heatmap. Discuss which features appear most related.

In [ ]:
# Criteria: Heatmap present. Notable correlations identified and discussed.

- Keep the target column separate and do not use it during clustering.

<a id='section32'></a>
### **Task 2 - Preprocessing & Feature Engineering**

- Encode categorical features appropriately.

In [ ]:
# Criteria: Correct encoding. Scaling method justified.

- Normalise or standardise features. Justify your choice of method.

**Step A - PCA:**

*Note:* PCA is used here for visualisation purposes only. Clustering in Tasks 3–5 will be performed on the scaled feature set selected in Step B.

- Plot the explained variance ratio per component and cumulatively.

- Select the number of components that explain at least 85% of variance.

- Visualise the data in the first two principal components.

In [ ]:
# Criteria: Variance plot correct. Component count justified. 2D scatter shown.

**Step B - Feature selection:**

- Split the data into training and test sets before applying feature selection. This is the only step where the target label may be used - supervised feature selection methods (as covered in the course) require it. The test set and the target label must not be used again after this point.

- Apply at least one feature selection method covered in the course on the training set.

- Compare the selected feature subset with the components identified by PCA. Do they capture similar structure?

- Justify which features you will retain for clustering, and why.

In [ ]:
# Criteria: At least one method applied. Comparison with PCA discussed.
## Final representation justified.

<a id='section33'></a>
### **Task 3 - Clustering: K-Means**

- Apply K-Means for values of k from 2 to 10.

- Use the Elbow Method (inertia / cost) to identify the optimal k.

- Also compute the Silhouette Score for each k and plot it.

In [ ]:
# Criteria: Both plots produced and interpreted.
## Optimal k selected with justification.

- Fit the final K-Means model with your chosen k and visualize the clusters in PCA space.

In [ ]:
# Criteria: Cluster assignments plotted in PCA space. Centres reported.

- Visualise the cluster assignments by projecting the data into PCA space (2D). Report and interpret the cluster centres directly in the original feature space, which features are highest or lowest for each group?

In [ ]:
# Criteria: Feature-level description of each cluster provided.

<a id='section34'></a>
### **Task 4 - Clustering: Gaussian Mixture Models**

- Fit GMMs with a varying number of components (2 to 10).

- Use BIC or AIC to select the optimal number of components. Plot the selected method curve.

In [ ]:
# Criteria: Both curves plotted. Optimal components selected and justified.

- Visualise the cluster assignments by projecting the data into PCA space (2D). Report and interpret the cluster centres directly in the original feature space, which features are highest or lowest for each group?

In [ ]:
# Criteria: Cluster assignments plotted in PCA space. Centres reported.

- Compare the hard cluster assignments from GMM with K-Means. Where do they agree and disagree?

In [ ]:
# Criteria: Agreements and disagreements discussed with examples.

<a id='section35'></a>
### **Task 5 - Clustering: Hierarchical Clustering**

- Compute a dendrogram using at least two linkage methods (e.g. Ward, complete, average).

In [ ]:
# Criteria: Two linkage methods compared. Dendrogram plotted clearly.

- Choose a cut point on the dendrogram and justify your choice.

In [ ]:
# Criteria: Cut justified. Clusters visualised in PCA space.

- Visualise the cluster assignments by projecting the data into PCA space (2D). Report and interpret the cluster centres directly in the original feature space, which features are highest or lowest for each group?.

- Discuss how hierarchical clustering differs structurally from the previous two methods.

In [ ]:
# Criteria: Conceptual differences vs K-Means/GMM discussed.

<a id='section36'></a>
### **Task 6 - Evaluation Against Ground Truth**

Now reveal the target label and evaluate your clustering results:

- Compute the Adjusted Rand Index (ARI) for each method.

In [ ]:
# Criteria: Computed correctly for all three methods. Results tabulated.

- Plot a confusion-style matrix showing how clusters map to the binary target (disease / no disease).

In [ ]:
# Criteria: Matrix plotted. Best method identified and explanation is data-driven.

- Which method best recovered the true patient groups? Discuss why, referencing the nature of the data and the assumptions of each algorithm.